#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# DISPLAY SETUP

# sets up monitors
if [ -x "$HOME/scripts/monitors" ];then
    bash "$HOME/scripts/monitors"
fi

# defines keyboard layout
setxkbmap -layout de

# launches polybar
if [ -x /usr/bin/polybar ]; then
    bash "$HOME/.config/polybar/launch.sh"
fi

# sets wallpaper

# fix mouse cursor
xsetroot -cursor_name left_ptr

# AUTOSTART APPLICATIONS

/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
/usr/lib/geoclue-2.0/demos/agent &
feh --bg-fill ~/.config/bspwm/wall.jpg &
redshift &
picom --experimental-backends &
dunst &

# BSPWM SETTINGS

bspc config border_width         2
bspc config window_gap          10

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

bspc config normal_border_color	 "#928374"
bspc config active_border_color	 "#e78a4e"
bspc config focused_border_color	 "#e78a4e"
bspc config presel_feedback_color	 "#e78a4e"
bspc config urgent_border_color 	 "#ea6962"

# BSPWM RULES

bspc rule -a zoom state=floating
bspc rule -a Emacs state=tiled
bspc rule -a R_x11 state=floating
